package controllers;

public enum Command {
     CREATE_PRODUCT,EXIT,
    ADD_PRODUCT, CANCEL_PRODUCT,
    SEARCH_PRODUCT,HOME_STORE,ADD_STORE,OPEN_STORE,UPDATE_STORE,
    CREATE_STORE,CANCEL_STORE,SET_UNIT,CANCEL_UNIT,
    UPDATE_PRODUCT,MODIFY_PRODUCT,DELETE_PRODUCT,SET_PRODUCT;
}
